const router = require('express').Router();
const auth = require('../controllers/auth');
const admin = require('../controllers/admin');
const search = require('../controllers/search');
const account = require('../controllers/account');
const gallery = require('../controllers/gallery');
const products = require('../controllers/products');
const loginInner = require('../controllers/login-inner');
const signupInner = require('../controllers/signup-inner');
const loginGoogle = require('../controllers/login-google');
const signupGoogle = require('../controllers/signup-google');
const contactMessage = require('../controllers/contact-message');
const emailVerification = require('../controllers/email-verification');
const passwordRecovery = require('../controllers/password-recovery');
const { authLimiter } = require('../middlewares/rateLimit');

router.use("/auth", auth);
router.use("/admin", admin);
router.use("/search", search);
router.use("/account", account);
router.use("/gallery", gallery);
router.use("/products", products);
router.use("/login-inner", authLimiter, loginInner);
router.use("/signup-inner", authLimiter, signupInner);
router.use("/login-google", loginGoogle);
router.use("/signup-google", signupGoogle);
router.use("/contact-message", authLimiter, contactMessage);
router.use("/email-verification", authLimiter, emailVerification);
router.use("/password-recovery", authLimiter, passwordRecovery);

module.exports = router;
